GET http://localhost:7000/api/users
###

GET http://localhost:7000/api/registrations/id/3
### log in
POST http://localhost:7000/api/auth/register
Content-Type: application/json

{
  "name": "user4",
  "email": "user4@email.dk",
  "phone": "12345678",
  "password": "1234"
}
###
POST http://localhost:7000/api/auth/login
Content-Type: application/json

{
  "email": "user5@email.dk",
"password": "1234"
}
### get in with Json Web Token
POST http://localhost:7000/api/protected/user
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJUaG9tYXMgSGFydG1hbm4iLCJzdWIiOiJ1c2VyQGVtYWlsLmRrIiwiZXhwIjoxNzEyNTI3MDQ5LCJlbWFpbCI6InVzZXJAZW1haWwuZGsiLCJyb2xlcyI6InVzZXIifQ.RXh0yC0bgWqA08Kq8BRYfGxoWKcKYCPtzCBTuUkHkM4
###
POST http://localhost:7000/api/events
Content-Type: application/json

{
  "title": "Event1",
  "description": "This is event 1",
  "date": "2024-01-02",
  "time": "10:00:00",
  "duration": "120",
  "capacity": "100",
  "location": "Location 1",
  "image": "image1.png",
  "status": "ACTIVE"
}
###

GET http://localhost:7000/api/registrations/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJHcnVwcGU0Iiwic3ViIjoidXNlcjVAZW1haWwuZGsiLCJleHAiOjE3MTI1MzkwODksImVtYWlsIjoidXNlcjVAZW1haWwuZGsiLCJyb2xlcyI6IkFETUlOIn0.n2-S8HaS2013qxYaA3vTrqMfB1V_EJh24HOjN1z3tEQ
