GET http://localhost:7000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJHcnVwcGU0Iiwic3ViIjoidXNlcjNAZW1haWwuZGsiLCJleHAiOjE3MTM2MjM4MDYsImVtYWlsIjoidXNlcjNAZW1haWwuZGsiLCJyb2xlcyI6InVzZXIifQ.0N96qzL40B3LWHxbNGq5ix1ZIhu-7_bUYHuZsQMC8Wg
###

GET http://localhost:7000/api/registrations/id/1
### oprette bruger
POST http://localhost:7000/api/auth/register
Content-Type: application/json

{
  "name": "user8",
  "email": "user8@email.dk",
  "phone": "12345678",
  "password": "1234"
}
###login
POST http://localhost:7000/api/auth/login
Content-Type: application/json

{
  "email": "user3@email.dk",
"password": "1234"
}
###oprete event
POST http://localhost:7000/api/events
Content-Type: application/json

{
  "title": "Event2",
  "description": "This is event 2",
  "date": "2024-01-02",
  "time": "10:00:00",
  "duration": "120",
  "capacity": "100",
  "location": "Location 1",
  "image": "image1.png",
  "status": "ACTIVE"
}
###alle registeringer
GET http://localhost:7000/api/registrations/

### vi giver event id 1 til user id 3 så event id i link og user id i body
POST http://localhost:7000/api/registrations/8
Content-Type: text/plain


6
### se kun bruger registering ud fra id
GET http://localhost:7000/api/registrations/id/2

### selette registering ud fra id
DELETE http://localhost:7000/api/registrations/2
###

GET http://localhost:7000/api/users/user/user4@email.dk
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJHcnVwcGU0Iiwic3ViIjoidXNlcjNAZW1haWwuZGsiLCJleHAiOjE3MTM1NDk1NjcsImVtYWlsIjoidXNlcjNAZW1haWwuZGsiLCJyb2xlcyI6InVzZXIifQ.Kpyf9Yd0QXmBAhsUczGkdEVIyrq8XPsSjJ6YrgB1ua0
###

GET http://localhost:7000/api/users/
